modified application
fatuma65/contact-list pull request #3
Opened 2023-10-24 07:23 UTC by fatuma65

Created an end point to retrieve a single contact from the database.
Created a post request to add a new contact to the list using the unique id generated.
Validated if the user has entered the correct contact details.

2023-10-24 08:39 UTC, sanya-kenneth requested changes
When doing a delete we don't expect the user to send data in the request unless otherwise

Get rid of the validation checks from line 158 to 171 because we are not updating any data but looking at deleting a resource.

Add extra validation to cater for a scenario where a user tries to add a contact with a phone number that exists in the db

Change the get single contact endpoint to /contact/<contact_id> for consistency

2023-10-24 08:39 UTC, sanya-kenneth commented on app.py
> +    data = request.get_json()
When doing a delete we don't expect the user to send data in the request unless otherwise

2023-10-24 08:39 UTC, sanya-kenneth commented on app.py
> +    if not first_name:
@fatuma65 Get rid of the validation checks from line 158 to 171 because we are not updating any data but looking at deleting a resource.

2023-10-24 08:39 UTC, sanya-kenneth commented on app.py
> +    if len(phone_number) < 10:
@fatuma65 Add extra validation to cater for a scenario where a user tries to add a contact with a phone number that exists in the db

2023-10-24 08:39 UTC, sanya-kenneth commented on app.py
> +@app.route('/list/<id>', methods=['GET'])
@fatuma65 Change this endpoint to `/contact/<contact_id>` for consistency

2023-10-24 14:17 UTC, fatuma65 commented on app.py
> +    if not first_name:
Okay, changes are made

2023-10-24 14:19 UTC, fatuma65 commented on app.py
> +@app.route('/list/<id>', methods=['GET'])
Okay

2023-10-25 09:27 UTC, sanya-kenneth commented
@fatuma65 code LGTM

2023-10-25 09:27 UTC, merged